// REe Official Taxonomy — categories, subcategories, sizes, colors, fabrics, condition grades

export const CATEGORIES = [
  "Tops",
  "Bottoms",
  "Dresses",
  "Outerwear",
  "Knitwear",
  "Activewear",
  "Swimwear",
  "Accessories",
  "Shoes",
  "Bags",
  "Jewelry",
  "Kids",
];

export const SUBCATEGORIES = {
  Tops: [
    "T-Shirt",
    "Blouse",
    "Shirt",
    "Dress Shirt",
    "Polo",
    "Tank Top",
    "Crop Top",
    "Bodysuit",
    "Camisole",
    "Tunic",
    "Henley",
  ],
  Bottoms: [
    "Jeans",
    "Trousers",
    "Shorts",
    "Skirt",
    "Mini Skirt",
    "Midi Skirt",
    "Maxi Skirt",
    "Leggings",
    "Culottes",
    "Cargo Pants",
    "Chinos",
    "Joggers",
    "Wide Leg Pants",
  ],
  Dresses: [
    "Midi Dress",
    "Maxi Dress",
    "Mini Dress",
    "Wrap Dress",
    "Shirt Dress",
    "Slip Dress",
    "A-Line Dress",
    "Bodycon Dress",
    "Cocktail Dress",
    "Evening Gown",
    "Sundress",
  ],
  Outerwear: [
    "Blazer",
    "Coat",
    "Jacket",
    "Bomber Jacket",
    "Biker Jacket",
    "Denim Jacket",
    "Parka",
    "Trench Coat",
    "Puffer Jacket",
    "Windbreaker",
    "Cape",
    "Vest",
    "Gilet",
  ],
  Knitwear: [
    "Sweater",
    "Cardigan",
    "Pullover",
    "Hoodie",
    "Turtleneck",
    "V-Neck Knit",
    "Crew Neck Knit",
    "Knit Vest",
  ],
  Activewear: [
    "Sports Bra",
    "Leggings",
    "Track Pants",
    "Running Shorts",
    "Workout Top",
    "Yoga Pants",
    "Sweatshirt",
    "Athletic Jacket",
  ],
  Swimwear: [
    "Bikini",
    "One-Piece Swimsuit",
    "Swim Trunks",
    "Cover-Up",
    "Rash Guard",
  ],
  Accessories: [
    "Scarf",
    "Belt",
    "Hat",
    "Cap",
    "Beanie",
    "Gloves",
    "Sunglasses",
    "Watch",
    "Wallet",
    "Tie",
    "Bow Tie",
    "Hair Accessory",
  ],
  Shoes: [
    "Sneakers",
    "Boots",
    "Ankle Boots",
    "Heels",
    "Sandals",
    "Loafers",
    "Flats",
    "Espadrilles",
    "Oxfords",
    "Mules",
    "Slides",
    "Platform Shoes",
  ],
  Bags: [
    "Tote Bag",
    "Crossbody Bag",
    "Shoulder Bag",
    "Clutch",
    "Backpack",
    "Bucket Bag",
    "Satchel",
    "Messenger Bag",
    "Wallet",
    "Pouch",
    "Belt Bag",
  ],
  Jewelry: [
    "Necklace",
    "Bracelet",
    "Ring",
    "Earrings",
    "Brooch",
    "Anklet",
    "Pendant",
    "Cufflinks",
  ],
  Kids: [
    "Kids T-Shirt",
    "Kids Dress",
    "Kids Jacket",
    "Kids Pants",
    "Kids Shorts",
    "Kids Sweater",
    "Kids Shoes",
    "Kids Accessories",
  ],
};

// Flat list of all subcategories for validation
export const ALL_SUBCATEGORIES = Object.values(SUBCATEGORIES).flat();

export const CONDITION_GRADES = ["A", "B", "C"];

export const CONDITION_DESCRIPTIONS = {
  A: "Like new — no visible wear, stains, or defects",
  B: "Good — minor signs of wear, no major flaws",
  C: "Fair — visible wear, minor flaws present",
};

export const NORMALIZED_COLORS = [
  "black",
  "white",
  "grey",
  "beige",
  "cream",
  "navy",
  "blue",
  "light blue",
  "red",
  "burgundy",
  "pink",
  "blush",
  "green",
  "olive",
  "khaki",
  "yellow",
  "mustard",
  "orange",
  "brown",
  "tan",
  "camel",
  "purple",
  "lavender",
  "gold",
  "silver",
  "coral",
  "teal",
  "mint",
  "multicolor",
];

export const NORMALIZED_FABRICS = [
  "Cotton",
  "Organic Cotton",
  "Linen",
  "Silk",
  "Wool",
  "Cashmere",
  "Merino Wool",
  "Denim",
  "Leather",
  "Faux Leather",
  "Suede",
  "Velvet",
  "Satin",
  "Chiffon",
  "Nylon",
  "Polyester",
  "Viscose",
  "Rayon",
  "Spandex",
  "Elastane",
  "Acrylic",
  "Fleece",
  "Jersey",
  "Tweed",
  "Corduroy",
  "Canvas",
  "Organza",
  "Tulle",
  "Modal",
  "Tencel",
  "Lyocell",
  "Hemp",
  "Bamboo",
];

// Size normalization maps
export const SIZE_ALIASES = {
  xs: "XS",
  "x-small": "XS",
  "extra small": "XS",
  s: "S",
  small: "S",
  m: "M",
  medium: "M",
  med: "M",
  l: "L",
  large: "L",
  xl: "XL",
  "x-large": "XL",
  "extra large": "XL",
  xxl: "XXL",
  "2xl": "XXL",
  "xx-large": "XXL",
  xxxl: "XXXL",
  "3xl": "XXXL",
  os: "One Size",
  "one size": "One Size",
  "one size fits all": "One Size",
};

// EU ↔ standard size mapping
export const EU_SIZE_MAP = {
  32: "XXS",
  34: "XS",
  36: "S",
  38: "M",
  40: "M",
  42: "L",
  44: "XL",
  46: "XXL",
  48: "XXXL",
};

export const IT_SIZE_MAP = {
  38: "XXS",
  40: "XS",
  42: "S",
  44: "M",
  46: "L",
  48: "XL",
  50: "XXL",
};

// Category groups for size validation
// Shoes use numeric sizing (EU 36-48, US 5-14, UK 3-12)
// Accessories/Jewelry/Bags typically use One Size or S/M/L
export const SHOE_CATEGORIES = ["Shoes"];
export const ACCESSORY_CATEGORIES = ["Accessories", "Jewelry", "Bags"];

// Shoe size ranges by system
export const SHOE_SIZE_RANGES = {
  EU: { min: 35, max: 48 },
  US: { min: 4, max: 16 },
  UK: { min: 2, max: 14 },
};

// Known brand list (expandable)
export const KNOWN_BRANDS = [
  "Acne Studios",
  "Adidas",
  "Alexander McQueen",
  "Balenciaga",
  "Balmain",
  "Bottega Veneta",
  "Burberry",
  "Calvin Klein",
  "Celine",
  "Chanel",
  "Chloé",
  "Coach",
  "COS",
  "Diesel",
  "Dior",
  "DKNY",
  "Dolce & Gabbana",
  "Fendi",
  "Ganni",
  "Givenchy",
  "Gucci",
  "H&M",
  "Hermès",
  "Hugo Boss",
  "Isabel Marant",
  "Jack & Jones",
  "Kenzo",
  "Lacoste",
  "Levi's",
  "Loewe",
  "Louis Vuitton",
  "Maison Margiela",
  "Mango",
  "Marc Jacobs",
  "Max Mara",
  "Michael Kors",
  "Miu Miu",
  "Moncler",
  "Moschino",
  "Nike",
  "Norse Projects",
  "Off-White",
  "Oscar de la Renta",
  "Prada",
  "Ralph Lauren",
  "Rag & Bone",
  "Saint Laurent",
  "Salvatore Ferragamo",
  "Sandro",
  "Stella McCartney",
  "Stüssy",
  "Ted Baker",
  "The North Face",
  "Theory",
  "Tiger of Sweden",
  "Tommy Hilfiger",
  "Valentino",
  "Versace",
  "Vivienne Westwood",
  "Zadig & Voltaire",
  "Zara",
];
