import { Inria_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Fashion App",
  description: "Generated by create next app",
};

const inriaSans = Inria_Sans({
  subsets: ["latin"], // Correct subset
  weight: ["300", "400", "700"], // Only supported weights
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inriaSans.className}>
      <body>
        <Providers>{children}</Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
