import dbConnect from "@/lib/db";
import Product from "@/models/Product";
import { BASE_URL } from "@/lib/seo";

/**
 * Dynamic sitemap.xml — generated by Next.js at request time.
 * Accessible at: https://re-e.dk/sitemap.xml
 *
 * Includes:
 *  - Static public pages (home, contact, legal)
 *  - Every publicly available product page (not sold, not archived)
 */

const staticRoutes = [
  {
    url: BASE_URL,
    lastModified: new Date(),
    changeFrequency: "daily",
    priority: 1.0,
  },
  {
    url: `${BASE_URL}/contact-support`,
    lastModified: new Date(),
    changeFrequency: "monthly",
    priority: 0.6,
  },
  {
    url: `${BASE_URL}/privacy-policy`,
    lastModified: new Date(),
    changeFrequency: "yearly",
    priority: 0.3,
  },
  {
    url: `${BASE_URL}/data-deletion`,
    lastModified: new Date(),
    changeFrequency: "yearly",
    priority: 0.2,
  },
];

export default async function sitemap() {
  try {
    await dbConnect();

    // Only include active, publicly visible products
    const products = await Product.find(
      { sold: false, archived: false, isDemo: false },
      { _id: 1, createdAt: 1 }
    )
      .sort({ createdAt: -1 })
      .lean();

    const productRoutes = products.map((product) => ({
      url: `${BASE_URL}/product/${product._id.toString()}`,
      lastModified: product.createdAt ?? new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    }));

    return [...staticRoutes, ...productRoutes];
  } catch (error) {
    // If the DB is unreachable during build, fall back to static routes only
    console.error("[sitemap] Failed to fetch products:", error);
    return staticRoutes;
  }
}
